---
- name: Add Centos repo
  yum_repository:
    name: centos
    description: Centos main repo
    baseurl: "{{ centos_repo_url }}"
    gpgkey: "{{ centos_repo_gpg_key_url }}"
    gpgcheck: yes
    enabled: yes

- name: Disable Main Centos repo.
  yum_repository:
    name: centos
    enabled: yes
  when: centos_repo_disable
